package swing.frame.finalaitics;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by alpu1014 on 07.08.2015.
 */
public class FinForm {
    private JTextField monthlyIncome;
    private JTextField savingsRate;
    private JTextField textField4;
    private JButton calculateButton;
    private JPanel panel1;
    private JButton button1;
    private JTextField rateOfReturn;
    private JLabel monthlyIncomeLabel;
    private JLabel savingsRateLabel;
    private JLabel rateOfReturnLabel;
    private JTextField numberOfMonths;
    private JLabel numberOfMonthsLabel;

    public FinForm() {
        calculateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("btn2");
            }
        });


    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("FinForm");
        frame.setContentPane(new FinForm().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        monthlyIncome = new JTextField();
        monthlyIncome.setText("");
        panel1.add(monthlyIncome, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(334, 24), null, 0, false));
        savingsRate = new JTextField();
        savingsRate.setText("");
        panel1.add(savingsRate, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(334, 24), null, 0, false));
        rateOfReturn = new JTextField();
        rateOfReturn.setText("");
        panel1.add(rateOfReturn, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(334, 17), null, 0, false));
        monthlyIncomeLabel = new JLabel();
        monthlyIncomeLabel.setText("Monthly income");
        panel1.add(monthlyIncomeLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(149, 16), null, 0, false));
        savingsRateLabel = new JLabel();
        savingsRateLabel.setText("Savings rate");
        panel1.add(savingsRateLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(149, 16), null, 0, false));
        rateOfReturnLabel = new JLabel();
        rateOfReturnLabel.setText("Rate of return");
        panel1.add(rateOfReturnLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(149, 17), null, 0, false));
        numberOfMonthsLabel = new JLabel();
        numberOfMonthsLabel.setText("Number of months");
        panel1.add(numberOfMonthsLabel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(149, 27), null, 0, false));
        numberOfMonths = new JTextField();
        panel1.add(numberOfMonths, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(334, 27), null, 0, false));
        textField4 = new JTextField();
        panel1.add(textField4, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(334, 24), null, 0, false));
        calculateButton = new JButton();
        calculateButton.setText("Calculate");
        panel1.add(calculateButton, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
